spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/jira
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GitHub_ID}
            client-secret: ${GitHub_secret}
          google:
            client-id: ${Google_ID}
            client-secret: ${Google_secret}
          gitlab:
            client-id: ${GitLab_ID}
            client-secret: ${GitLab_secret}

#  mail:
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true
#    host: ${Mail_host}
#    username: ${Mail_username}
#    password: ${Mail_password}
#    port: ${Mail_port}

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: jira4jr@gmail.com
    password: zdfzsrqvgimldzyj
    port: 587